ktor:
  application:
    modules:
      - com.example.ApplicationKt.module
  deployment:
    port: 8080
postgres:
  url: "jdbc:postgresql://aws-0-us-east-2.pooler.supabase.com:5432/postgres?user=postgres.ysyinmlojpglnjteeeks&password=RjChicago23!"
  user: postgres
  password: "RjChicago23!"
